SpaceToChannel: 
    apply: True
    repeat: [0,3,1]

max_blocks: 6

common:
    repeat: [[1,3], [1,5], [1,5], [1,5], [1,5], [1,5]]
    out_channels: [[12,132,12], [12,132,12], [12,132,12], [12,252,12], [12,252,12],[12,516,12]]
    stride: [2,1,2,1,2,1] # -1 = 1~2 search
    activation: ["ReLU","Hardswish"]

blocks:
    Conv:
      start: 0
      kernel: [[1,5,2], [1,5,2], [1,5,2], [1,5,2], [1,5,2], [1,5,2]] # low,high,step
      
    DWConv:
      start: 0
      kernel: [[1,5,2], [1,5,2], [1,5,2], [1,5,2], [1,5,2], [1,5,2]]
    
    InvertedResidualv2:
      start: 0
      c: [[12,36,12], [12,36,12], [8,32,8], [8,64,8], [12,132,12], [12,132,12]]
      t: [[1,4], [1,4], [1,8], [1,8], [1,8], [1,8]]
    
    InvertedResidualv3:
      start: 0
      kernel: [[3,5,2], [3,5,2], [3,5,2], [3,5,2], [3,5,2], [3,5,2]]
      c: [[12,36,12], [12,36,12], [12,48,12], [12,84,12], [12,84,12], [12,156,12]]
      t: [[1.0,6.0,0.1], [1.0,6.0,0.1], [1.0,6.0,0.1], [1.0,6.0,0.1], [1.0,6.0,0.1], [1.0,6.0,0.1]]
      se: [[0,1], [0,1], [0,1], [0,1], [0,1], [0,1]]
      hs: [[0,1], [0,1], [0,1], [0,1], [0,1], [0,1]]
    
    InvertedResidual:
      start: 0
      multi: [[0,1,1], [0,1,1], [0,1,1], [0,1,1], [0,1,1], [0,1,1]]
      kernel: [[3,5,2], [3,5,2], [3,5,2], [3,5,2], [3,5,2], [3,5,2]]
      exp_ratio: [[4.0, 6.0, 2.0], [4.0, 6.0, 2.0], [4.0, 6.0, 2.0], [4.0, 6.0, 2.0], [4.0, 6.0, 2.0], [4.0, 6.0, 2.0]]
      se_ratio: [[0.25, 1.0, 0.25], [0.25, 1.0, 0.25], [0.25, 1.0, 0.25], [0.25, 1.0, 0.25], [0.25, 1.0, 0.25], [0.25, 1.0, 0.25]]
    
    Pass:
      start: 0

Classifier:
  last_dim: [132,528,132]
  num_classes: 9